#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-typhoeus
Version  : 0.8.0
Release  : 4
URL      : https://rubygems.org/downloads/typhoeus-0.8.0.gem
Source0  : https://rubygems.org/downloads/typhoeus-0.8.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-ethon
BuildRequires : rubygem-faraday
BuildRequires : rubygem-ffi
BuildRequires : rubygem-guard-rspec
BuildRequires : rubygem-multipart-post
BuildRequires : rubygem-rack
BuildRequires : rubygem-rack-protection
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-sinatra
BuildRequires : rubygem-tilt

%description
# Typhoeus [![Build Status](https://img.shields.io/travis/typhoeus/typhoeus/master.svg)](https://travis-ci.org/typhoeus/typhoeus) [![Code Climate](https://img.shields.io/codeclimate/github/typhoeus/typhoeus.svg)](https://codeclimate.com/github/typhoeus/typhoeus) [![Gem Version](https://img.shields.io/gem/v/typhoeus.svg)](https://rubygems.org/gems/typhoeus)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n typhoeus-0.8.0
gem spec %{SOURCE0} -l --ruby > rubygem-typhoeus.gemspec

%build
gem build rubygem-typhoeus.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
typhoeus-0.8.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/typhoeus-0.7.2 && sed -i -e '/require "bundler"/ s/^/#/' -e '/Bundler\.setup/ s/^/#/' spec/spec_helper.rb && rspec -I.:lib spec/ && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/typhoeus-0.8.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Faraday/Adapter/Typhoeus/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Faraday/Adapter/Typhoeus/cdesc-Typhoeus.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Faraday/Adapter/Typhoeus/configure_proxy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Faraday/Adapter/Typhoeus/configure_socket-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Faraday/Adapter/Typhoeus/configure_ssl-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Faraday/Adapter/Typhoeus/configure_timeout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Faraday/Adapter/Typhoeus/parallel%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Faraday/Adapter/Typhoeus/perform_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Faraday/Adapter/Typhoeus/read_body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Faraday/Adapter/Typhoeus/request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Faraday/Adapter/Typhoeus/setup_parallel_manager-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Faraday/Adapter/cdesc-Adapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Faraday/cdesc-Faraday.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rack/Typhoeus/Middleware/ParamsDecoder/Helper/cdesc-Helper.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rack/Typhoeus/Middleware/ParamsDecoder/Helper/convert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rack/Typhoeus/Middleware/ParamsDecoder/Helper/decode%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rack/Typhoeus/Middleware/ParamsDecoder/Helper/decode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rack/Typhoeus/Middleware/ParamsDecoder/Helper/decode_typhoeus_arrays-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rack/Typhoeus/Middleware/ParamsDecoder/Helper/encoded%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rack/Typhoeus/Middleware/ParamsDecoder/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rack/Typhoeus/Middleware/ParamsDecoder/cdesc-ParamsDecoder.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rack/Typhoeus/Middleware/ParamsDecoder/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rack/Typhoeus/Middleware/ParamsDecoder/update_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rack/Typhoeus/Middleware/cdesc-Middleware.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rack/Typhoeus/cdesc-Typhoeus.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rack/cdesc-Rack.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rails/Typhoeus/Railtie/cdesc-Railtie.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rails/Typhoeus/cdesc-Typhoeus.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Rails/cdesc-Rails.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Config/block_connection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Config/cache-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Config/cdesc-Config.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Config/memoize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Config/user_agent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Config/verbose-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/EasyFactory/cdesc-EasyFactory.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/EasyFactory/changed_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/EasyFactory/easy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/EasyFactory/get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/EasyFactory/hydra-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/EasyFactory/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/EasyFactory/provide_help-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/EasyFactory/removed_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/EasyFactory/renamed_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/EasyFactory/request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/EasyFactory/sanitize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/EasyFactory/sanitize_timeout%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/EasyFactory/set_callback-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Errors/NoStub/cdesc-NoStub.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Errors/NoStub/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Errors/TyphoeusError/cdesc-TyphoeusError.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Errors/cdesc-Errors.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/all-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/and_return-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/base_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/cdesc-Expectation.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/clear-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/find_by-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/matches%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/options_match%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/response_for-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/responses-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/stubbed_from-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Expectation/url_match%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Addable/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Addable/cdesc-Addable.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Before/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Before/cdesc-Before.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/BlockConnection/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/BlockConnection/cdesc-BlockConnection.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Cacheable/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Cacheable/cdesc-Cacheable.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Memoizable/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Memoizable/cdesc-Memoizable.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Memoizable/memory-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Memoizable/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Queueable/abort-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Queueable/cdesc-Queueable.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Queueable/dequeue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Queueable/dequeue_many-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Queueable/queue-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Queueable/queue_front-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Queueable/queued_requests-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Runnable/cdesc-Runnable.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Runnable/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Stubbable/add-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/Stubbable/cdesc-Stubbable.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/cdesc-Hydra.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/hydra-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/max_concurrency-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/multi-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Hydra/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Pool/cdesc-Pool.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Pool/clear-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Pool/easies-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Pool/get-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Pool/release-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Pool/with_easy-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Actions/cdesc-Actions.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Actions/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Actions/get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Actions/head-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Actions/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Actions/patch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Actions/post-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Actions/put-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Before/cdesc-Before.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Before/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/BlockConnection/blocked%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/BlockConnection/cdesc-BlockConnection.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/BlockConnection/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Cacheable/cache_ttl-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Cacheable/cacheable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Cacheable/cdesc-Cacheable.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Cacheable/response%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Cacheable/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Callbacks/Types/cdesc-Types.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Callbacks/cdesc-Callbacks.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Callbacks/execute_callbacks-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Callbacks/execute_headers_callbacks-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Marshal/cdesc-Marshal.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Marshal/marshal_dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Marshal/marshal_load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Memoizable/cdesc-Memoizable.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Memoizable/memoizable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Memoizable/response%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Operations/cdesc-Operations.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Operations/finish-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Operations/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Responseable/cdesc-Responseable.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Responseable/response%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Responseable/response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Streamable/cdesc-Streamable.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Streamable/on_body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Streamable/streaming%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Stubbable/cdesc-Stubbable.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/Stubbable/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/base_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/block_connection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/cache_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/cdesc-Request.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/encoded_body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/fuzzy_hash_eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/hashable_string_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/hydra-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/original_options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/set_defaults-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Request/url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Cacheable/cached%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Cacheable/cached-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Cacheable/cdesc-Cacheable.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Header/cdesc-Header.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Header/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Header/parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Header/process_line-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Header/process_pair-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Header/raw-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Header/set_default_proc_on-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Header/set_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/app_connect_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/appconnect_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/cdesc-Informations.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/connect_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/debug_info-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/effective_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/headers_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/httpauth_avail-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/name_lookup_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/namelookup_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/pretransfer_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/primary_ip-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/redirect_count-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/redirect_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/redirections-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/request_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/response_body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/response_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/response_headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/return_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/return_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/start_transfer_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/starttransfer_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Informations/total_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Status/cdesc-Status.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Status/http_version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Status/modified%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Status/status_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Status/success%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/Status/timed_out%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/cdesc-Response.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/handled_response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/mock%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/mock-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/Response/request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/before-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/cdesc-Typhoeus.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/configure-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/stub-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/Typhoeus/with_connection-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/typhoeus-0.8.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/CHANGELOG.md
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/Guardfile
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/UPGRADE.md
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/rack/typhoeus.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/rack/typhoeus/middleware/params_decoder.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/rack/typhoeus/middleware/params_decoder/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/adapters/faraday.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/config.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/easy_factory.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/errors.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/errors/no_stub.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/errors/typhoeus_error.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/expectation.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/addable.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/before.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/block_connection.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/cacheable.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/memoizable.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/queueable.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/runnable.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/hydra/stubbable.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/pool.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/railtie.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/actions.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/before.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/block_connection.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/cacheable.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/callbacks.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/marshal.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/memoizable.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/operations.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/responseable.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/streamable.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/request/stubbable.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/response.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/response/cacheable.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/response/header.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/response/informations.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/response/status.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/lib/typhoeus/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/perf/profile.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/perf/vs_nethttp.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/rack/typhoeus/middleware/params_decoder/helper_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/rack/typhoeus/middleware/params_decoder_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/support/localhost_server.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/support/memory_cache.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/support/server.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/adapters/faraday_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/config_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/easy_factory_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/errors/no_stub_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/expectation_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/hydra/addable_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/hydra/before_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/hydra/block_connection_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/hydra/cacheable_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/hydra/memoizable_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/hydra/queueable_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/hydra/runnable_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/hydra/stubbable_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/hydra_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/pool_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/request/actions_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/request/before_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/request/block_connection_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/request/cacheable_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/request/callbacks_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/request/marshal_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/request/memoizable_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/request/operations_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/request/responseable_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/request/stubbable_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/request_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/response/header_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/response/informations_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/response/status_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus/response_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/spec/typhoeus_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/typhoeus-0.8.0/typhoeus.gemspec
/usr/lib64/ruby/gems/2.2.0/specifications/typhoeus-0.8.0.gemspec
